name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Check Terraform
        shell: powershell
        run: |
          terraform version
